title: 26年分のエンジニアキャリアを棚卸しする
slug: about
emoji: 🏔️
type: idea
topics:
  - profile
  - engineer
  - freelance
  - aws
  - devsecops
published: false
paid: false
note:
  magazine: null
  price: null
zenn:
  publication_name: null
  includePaywalled: false
